I18n.hu =
  menu:
    schema: "Terv"
    new: "Új..."
    load: "Betöltés ..."
    save: "Mentés"
    save_as: "Mentés másként ..."
    templates: "Minták ..."
    properties: "Tulajdonságok ..."
    share: "Megosztás ..."
    import: "Importálás ..."
    edit: "Szerkesztés"
    undo: "Visszavonás"
    redo: "Újra"
    select_all: "Mindent kiválaszt"
    select_none: "Kiválasztás visszavonása"
    delete_selected: "Kiválasztottak törlése"
    insert: "Beilleszt"
    table: "Tábla"
    note: "Jegyzet"
    view: "Néz/nézet"
    show_minimap: "Áttekintő ablak megjelenítése"
    hide_minimap: "Áttekintő ablak elrejtése"
    show_sidebar: "Oldalsáv megjelenítése"
    hide_sidebar: "Oldalsáv elrejtése"
    show_grid: "Rács megjelenítése"
    hide_grid: "Rács elrejtése"
    sort_items: "Elemek rendezése"
    linetype: "Vonal típusa"
    bezier: "Bezier"
    cornered: "Sarkos"
    options: "Beállítások ..."
    export: "Exportálás"
    sql: "Sql ..."
    image: "Kép ..."
    help: "Segítség"
    index: "Index"
    changes: "Változások"
    shortcuts: "Gyorsbillentyűk"
    feedback: "Visszajelzés"
    about: "Névjegy"
    guest: "Vendég"
    login: "Bejelentkezés"
    logout: "Kijelentkezés"
    settings: "Beállítások"
  panel:
    history: "Előzmények"
    last_versions_label: "Az utolsó 10 verziója ennek a tervnek:"
    properties: "Tulajdonságok"
    properties_schema_name: "Terv neve:"
    properties_database: "Adatbázis:"
    comments: "Megjegyzések"
    comment_placeholder: "Ide írhat megjegyzést"
    send: "Küldés"
  dialog:
    new_schema: "Új tervezet"
    new_schema_title: "Cím"
    new_schema_database: "Adatbázis"
    new_schema_type_info: """"Általános" típusu adatbázis kiválasztása után csak általános adattípusokat határzhat meg, de SQL kódot minden adatbázishoz generálhatsz"""
    new_schema_create_new: "Új terv készítés"
    load_schema: "Terv betöltése"
    load_schema_your_schemas: "Terveid:"
    load_schema_schema_name: "Terv neve"
    load_schema_database: "Adatbázis"
    load_schema_last_save: "Utolsó mentés"
    load_schema_shared_with_you: "Veled megosztott tervek:"
    load_schema_owner: "Tulajdonos"
    load_schema_no_schemas: "Nincsenek tervek"
    load_schema_no_shared_schemas: "Nincsenek megosztott tervek"
    saveas: "Mentés másként"
    saveas_title: "Cím"
    saveas_button: "Mentés másként"
    templates: "Minták"
    templates_schema_name: "Minta neve"
    templates_database: "Adatbázis"
    templates_description: "Leírás"
    properties: "Terv tulajdonságai"
    properties_title: "Cím"
    properties_publish: "Mintaként közzétesz"
    properties_template_info: "(Minták mindenki számára elérhetőek)"
    properties_delete_schema: "Terv törlése"
    properties_delete_alert: "(Véglegesen törlődik az összes megjegyzéssel, hozzászólással)"
    properties_save: "Válzotások mentése"
    share: "Megoszt"
    share_info: "5 felhasználóval osztható meg a terv"
    share_email: "E-mail"
    share_access: "Access"
    share_read_only: "Read only"
    share_read_write: "Read and write"
    share_send_email: "Send invitation e-mail"
    share_invite_button: "Invite"
    share_collaborators: "Collaborators:"
    import: "Import Sql"
    login_email: "E-mail"
    login_password: "Password"
    login_button: "Login"
    login_forgot_password: "I forgot my password"
    options: "Options"
    options_line_colors: "Line Colors"
    options_invert_line_direction: "Invert line direction"
    options_show_fk_icon: "Show Foreign Key Icon"
    options_show_ai_icon: "Show Auto Increment Icon"
    options_show_not_null_icon: "Show Not Null icon"
    options_show_default_values: "Show Default Values"
    options_language: "Language"
    options_save_changes: "Save Changes"
    export_sql: "Export SQL"
    export_sql_generate: "Generate SQL"
    export_sql_download: "Download SQL file"
    export_image: "Export Image"
    export_image_zoomin: "Zoom in"
    export_image_zoomout: "Zoom out"
    export_image_reset: "Reset"
    export_image_open_in_new_tab: "Open image in new tab"
    help: "Help"
    shortcuts: "Keyboard Shortcuts"
    help_changelog: "Changes"
    feedback: "Feedback"
    feedback_type: "Feedback Type"
    feedback_bug: "Bug report"
    feedback_feature: "Feature Request"
    feedback_help: "Help"
    feedback_other: "Other"
    feedback_message: "Message"
    feedback_button: "Send Feedback"
    about: "About dbdesigner.net"
    user_settings: "User Settings"
    user_settings_username: "Username"
    user_settings_email: "E-mail"
    user_settings_save: "Save Changes"
    login: "Login"
    close: "Close"
    back: "Back"
    dirty_schema_confirmation: "Unsaved changes!"
    dirty_schema_confirmation_message: "You have unsaved changes in your schema, would you like to save it?"
    dirty_schema_confirmation_save_changes_button: "Save changes"
    dirty_schema_confirmation_discard_changes_and_continue_button: "Discard changes"
    dirty_schema_confirmation_cancel_button: "Cancel"
  designer:
    save_note_edit: "Save"
    cancel_note_edit: "Cancel"
    delete_note: "Delete"
    table_name: "Table Name"
    table_comment: "Table Comment"
    table_save: "Save"
    table_cancel: "Cancel"
    table_delete: "Delete Table"
    table_clone: "Clone Table"
    table_add_field: "Add field"
    field_name: "Name"
    field_type: "Type"
    field_size: "Size"
    field_default: "Default"
    field_unique: "Unique"
    field_allow_nulls: "Allow nulls"
    field_autoincrement: "Auto Increment"
    field_primary_key: "Primary Key"
    field_foreign_key: "Foreign Key"
    field_save: "Save"
    field_update: "Update"
    field_cancel: "Cancel"
    field_delete: "Delete Field"
    field_delete_alert: "Are you sure you want to delete this field?\n(hold shift to delete without confirmation)"
    field_ref_table: "Ref. Table"
    field_ref_field: "Ref. Field"
  alerts:
    delete_schema: "Are you sure you want to delete this schema?"
    server_error: "A server error occurred"
    schema_owner_error: "Only the schema owner can change share settings"
login_to_use_this_function: "You should login to use this function"
